language: python
python:
  - "3.9"
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run black --experimental-string-processing
  - poetry run flake8 --max-line-length=88 --extend-ignore=E203
  - poetry run pytest